# configure vscode yaml support https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
# yaml-language-server: $schema=https://fasterci.com/config.schema.json
workflows:
  - name: faster CI
    image: us.gcr.io/fasterci/bazelbuilder:d278ee1
    on:
      push:
        branches: [master]
      pull_request:
        branches: [master]
    steps:
      - name: bazel test
        bazel:
          build_targets: [//...]
          test_targets: [//...]
      - name: bazel test asan
        bazel:
          test_targets: [//tests/sanitizers:asan_test]
          test_flags: [--config, asan]
      - name: bazel test tsan
        bazel:
          test_targets: [//tests/sanitizers:tsan_test]
          test_flags: [--config, tsan]
      - name: bazel test ubsan
        bazel:
          test_targets: [//tests/sanitizers:ubsan_test]
          test_flags: [--config, ubsan]
