name: Default

on:
  push:
    branches: [master]
  pull_request:
    types: [labeled]

  # Allows manually triggering this workflow from the Actions tab.
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.label.name == 'ci-test' }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
        compilation_mode:
          - fastbuild
          - dbg
          - opt
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: |-
          set -o errexit -o nounset -o pipefail
          cp .github/workflows/.bazelrc.ci .bazelrc.user
          echo "${ENGFLOW_CLIENT_CRT}" > tourmaline-client.crt
          chmod 0600 tourmaline-client.crt
          echo "${ENGFLOW_PRIVATE_KEY}" > tourmaline-client.key
          chmod 0600 tourmaline-client.key
        env:
          ENGFLOW_CLIENT_CRT: ${{ secrets.ENGFLOW_CLIENT_CRT }}
          ENGFLOW_PRIVATE_KEY: ${{ secrets.ENGFLOW_PRIVATE_KEY }}
      - name: Test
        run: |-
          bazel test \
            --compilation_mode ${{ matrix.compilation_mode }} \
            //...
  sanitizers:
    if: ${{ github.event.label.name == 'ci-test' }}
    strategy:
      matrix:
        sanitizer:
          - asan
          - lsan
          - tsan
          - ubsan
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: |-
          set -o errexit -o nounset -o pipefail
          cp .github/workflows/.bazelrc.ci .bazelrc.user
          echo "${ENGFLOW_CLIENT_CRT}" > tourmaline-client.crt
          chmod 0600 tourmaline-client.crt
          echo "${ENGFLOW_PRIVATE_KEY}" > tourmaline-client.key
          chmod 0600 tourmaline-client.key
        env:
          ENGFLOW_CLIENT_CRT: ${{ secrets.ENGFLOW_CLIENT_CRT }}
          ENGFLOW_PRIVATE_KEY: ${{ secrets.ENGFLOW_PRIVATE_KEY }}
      - name: Test ${{ matrix.sanitizer }}
        run: |-
          bazel test \
            --config ${{ matrix.sanitizer }} \
            //tests/sanitizers:${{ matrix.sanitizer }}_test
  rbe:
    if: ${{ github.event.label.name == 'ci-test' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: |-
          set -o errexit -o nounset -o pipefail
          cp .github/workflows/.bazelrc.ci .bazelrc.user
          echo "${ENGFLOW_CLIENT_CRT}" > tourmaline-client.crt
          chmod 0600 tourmaline-client.crt
          echo "${ENGFLOW_PRIVATE_KEY}" > tourmaline-client.key
          chmod 0600 tourmaline-client.key
        env:
          ENGFLOW_CLIENT_CRT: ${{ secrets.ENGFLOW_CLIENT_CRT }}
          ENGFLOW_PRIVATE_KEY: ${{ secrets.ENGFLOW_PRIVATE_KEY }}
      - name: Test with RBE
        run: |-
          bazel test \
            --config rbe \
            //...
