name: Default

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]

  # Allows manually triggering this workflow from the Actions tab.
  workflow_dispatch:

jobs:
  distros:
    if: ${{ github.ref == 'refs/heads/main' }} or ${{ github.event.label.name == 'ci-test' }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test
        run: ./.github/workflows/engflow.sh --config engflow //...
        env:
          ENGFLOW_CLIENT_CRT: ${{ secrets.ENGFLOW_CLIENT_CRT }}
          ENGFLOW_PRIVATE_KEY: ${{ secrets.ENGFLOW_PRIVATE_KEY }}
  compilation_modes:
    if: ${{ github.ref == 'refs/heads/main' }} or ${{ github.event.label.name == 'ci-test' }}
    strategy:
      matrix:
        compilation_mode:
          - fastbuild
          - dbg
          - opt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test
        run: |-
          ./.github/workflows/engflow.sh \
            --config engflow \
            --compilation_mode ${{ matrix.compilation_mode }} \
            //...
        env:
          ENGFLOW_CLIENT_CRT: ${{ secrets.ENGFLOW_CLIENT_CRT }}
          ENGFLOW_PRIVATE_KEY: ${{ secrets.ENGFLOW_PRIVATE_KEY }}
  sanitizers:
    if: ${{ github.ref == 'refs/heads/main' }} or ${{ github.event.label.name == 'ci-test' }}
    strategy:
      matrix:
        sanitizer:
          - asan
          - lsan
          - tsan
          - ubsan
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test ${{ matrix.sanitizer }}
        run: |-
          ./.github/workflows/engflow.sh \
            --config engflow \
            --config ${{ matrix.sanitizer }} \
            //tests/sanitizers:${{ matrix.sanitizer }}_test
        env:
          ENGFLOW_CLIENT_CRT: ${{ secrets.ENGFLOW_CLIENT_CRT }}
          ENGFLOW_PRIVATE_KEY: ${{ secrets.ENGFLOW_PRIVATE_KEY }}
  rbe:
    if: ${{ github.ref == 'refs/heads/main' }} or ${{ github.event.label.name == 'ci-test' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Test with RBE
        run: |-
          ./.github/workflows/engflow.sh \
            --config rbe \
            --config engflow \
            --config engflow_rbe \
            //...
        env:
          ENGFLOW_CLIENT_CRT: ${{ secrets.ENGFLOW_CLIENT_CRT }}
          ENGFLOW_PRIVATE_KEY: ${{ secrets.ENGFLOW_PRIVATE_KEY }}
